name: ci
on:
   push:
      branches: main
jobs:
   build-and-deploy:
      runs-on: ubuntu-latest
      name: "Build and deploy to pypi"
      steps:
         - uses: actions/checkout@v2

         - uses: actions/setup-python@v2
           with:
              python-version: "3.11"
              architecture: "x64"

         - name: "Dependencies"
           run: |
              pip install poetry twine

         - name: "Publish"
           run: poetry publish --build --username __token__ --password ${{ secrets.PYPI_TOKEN }}
